###
# Copyright (2020) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
### 
---
#######################################################################
#
# Play: Generate vSphere template
#
#######################################################################
- name: Generate vSphere Template
  hosts: template
  force_handlers: true
  gather_facts: false
  roles:
  - role: template

#######################################################################
#
# Play: Provision Loadbalancer and Rancher VMs
#
#######################################################################
- name: Provision VMs
  hosts: all:!local:!template
  gather_facts: false
  roles:
  - role: vspherevm
    vars:
      provision: yes
      poweron: yes

#######################################################################
#
# Play: Update Pkg Manager
#
#######################################################################
- name: Update VMs
  hosts: all:!local:!template
  gather_facts: true
  roles:
  - role: osupdate
